### ISSUE TITLE
XVIZ Parser Error on running streetscape with KITTI example

### ISSUE THREAD

**Issue by pranaabdhawan** [uber/xviz#534]
Trying to run the Kitti demo with:
`./scripts/run-kitti-example.sh`
Getting the following error on Streetscape:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Float64Array.set (<anonymous>)
    at a3bc1741-2346-4c4b-abc1-14d441e0aa3e:8
    at p (a3bc1741-2346-4c4b-abc1-14d441e0aa3e:8)
    at a3bc1741-2346-4c4b-abc1-14d441e0aa3e:17
    at Array.forEach (<anonymous>)
    at a3bc1741-2346-4c4b-abc1-14d441e0aa3e:17
    at t.default (a3bc1741-2346-4c4b-abc1-14d441e0aa3e:17)
    at y (a3bc1741-2346-4c4b-abc1-14d441e0aa3e:8)
    at d (a3bc1741-2346-4c4b-abc1-14d441e0aa3e:8)
    at t.parseXVIZMessageSync (a3bc1741-2346-4c4b-abc1-14d441e0aa3e:8)
```
Am I missing something?

**Comment by zoeeer** [comment]
I had this too.

**I used XVIZ v1.0.1 to convert this data.**

I did some investigation and think the converted data contains something wrong.
I tried to convert this dataset to json format, by adding `--json` option when running `example/converter/website-demo-data.sh`,  and the output **2-frame.json** looked like this:

![image](https://user-images.githubusercontent.com/4843075/67077280-7971e400-f1c1-11e9-8d4a-42e6462716dd.png)

I guessed the error might be caused by the array of null values inside the `"/vehicle/trajectory":"polylines"::"vertices"` array. So I deleted the object containing vertices, making "polylines" an empty array, and I can parse this frame of data and display it in streescape.gl get-started demo.
